#!/bin/bash

NETCDFDIR=${NETCDFDIR-BROKEN}

export CC="${CC-gcc}"
export CPPFLAGS="${CPPFLAGS}"
export CFLAGS="${CFLAGS--I${NETCDFDIR}/include -fopenmp}"
export CXXFLAGS="${CXXFLAGS-${CFLAGS}}"
export FC="${FC-gfortran}"
export FCFLAGS="${FCFLAGS--I${NETCDFDIR}/include}"
export FFLAGS="${FFLAGS-${FCFLAGS}}"
export F77=${F77-gfortran}
export LIBS="${LIBS--L${NETCDFDIR}/lib -lhdf5_hl -lhdf5}"
export LDFLAGS="${LDFLAGS}"
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH-${NETCDFDIR}/lib}

make clean
set -xv
./configure --prefix=${NETCDFDIR} --enable-fortran --enable-hl --enable-static-exec --enable-parallel && make -j${NUMCORE-8} && make check
