#!/bin/bash

NETCDFDIR=${NETCDFDIR-BROKEN}

export CC="${CC-gcc}"
export CPPFLAGS="${CPPFLAGS}"
export CFLAGS="${CFLAGS--I${NETCDFDIR}/include -fopenmp}"
export CXXFLAGS="${CXXFLAGS-${CFLAGS}}"
export FC="${FC-gfortran}"
export FCFLAGS="${FCFLAGS--I${NETCDFDIR}/include}"
export FFLAGS="${FFLAGS-${FCFLAGS}}"
export F77=${F77-gfortran}
export LIBS="${LIBS--L${NETCDFDIR}/lib}"
export LDFLAGS="${LDFLAGS}"
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH-${NETCDFDIR}/lib}

make clean
./configure --prefix=${NETCDFDIR} && make -j${NUMCORE-8} && make install
